# Generated by Django 4.1.1 on 2022-10-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="board_id",),
    ]
