# Generated by Django 4.1.1 on 2022-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_remove_article_board_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="board",
            field=models.CharField(default="A", max_length=1, verbose_name="게시판"),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
